/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cpprint */

#ifndef _Included_cpprint
#define _Included_cpprint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cpprint
 * Method:    sayhi
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cpprint_sayhi
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

